<?php
$page_title = 'Report History';
require_once('includes/load.php');

// Check if the user has permission
page_require_level(1);

// Fetch the report history from the database
$report_history = fetch_report_history();
?>

<?php include_once('layouts/header.php'); ?>

<div class="row">
    <div class="col-12">
        <div class="card shadow-sm border-0">
            <div class="card-header bg-primary text-white d-flex align-items-center">
                <i class="bi bi-clock-history me-2"></i>
                <h5 class="mb-0">Report History</h5>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover align-middle">
                        <thead class="table-light">
                            <tr>
                                <th scope="col">Report ID</th>
                                <th scope="col">Generated By</th>
                                <th scope="col">Location</th>
                                <th scope="col">Report Type</th>
                                <th scope="col">Date Generated</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($report_history as $report): ?>
                                <tr>
                                    <td><?php echo $report['id']; ?></td>
                                    <td><?php echo get_user_by_id($report['generated_by'])['username']; ?></td>
                                    <td><?php echo get_location_name($report['location_id']); ?></td>
                                    <td><?php echo $report['report_type']; ?></td>
                                    <td><?php echo date('Y-m-d H:i:s', strtotime($report['generated_at'])); ?></td>
                                    <td>
                                        <?php if (!empty($report['file_path'])): ?>
                                            <a href="<?php echo $report['file_path']; ?>" class="btn btn-primary btn-sm">
                                                <i class="bi bi-download"></i> Download
                                            </a>
                                        <?php else: ?>
                                            <span class="text-muted">N/A</span>
                                        <?php endif; ?>
                                    </td>
                                </tr>
                            <?php endforeach; ?>
                            <?php if (empty($report_history)): ?>
                                <tr>
                                    <td colspan="6" class="text-center text-muted">No reports available.</td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<?php include_once('layouts/footer.php'); ?>
