<?php
$page_title = 'Report History';
require_once('includes/load.php');

// Check if the user has permission
page_require_level(1);

// Fetch the report history from the database
$report_history = fetch_report_history();
?>

<?php include_once('layouts/header.php'); ?>

<div class="row">
    <div class="col-md-12">
        <h3>Report History</h3>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Report ID</th>
                    <th>Generated By</th>
                    <th>Location</th>
                    <th>Report Type</th>
                    <th>Date Generated</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($report_history as $report): ?>
                    <tr>
                        <td><?php echo $report['id']; ?></td>
                        <td><?php echo get_user_by_id($report['generated_by'])['username']; ?></td>
                        <td><?php echo get_location_name($report['location_id']); ?></td>
                        <td><?php echo $report['report_type']; ?></td>
                        <td><?php echo date('Y-m-d H:i:s', strtotime($report['generated_at'])); ?></td>
                        <td>
                            <!-- Link to view/download the report if file path exists -->
                            <?php if (!empty($report['file_path'])): ?>
                                <a href="<?php echo $report['file_path']; ?>" class="btn btn-primary">Download</a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include_once('layouts/footer.php'); ?>
